// Typed access to the SRD 5.2 data generated by scripts/import-srd.mjs.
// Spells live in ./spells (a separate entry point) so clients can load them lazily.
import armorJson from './data/armor.json';
import backgroundsJson from './data/backgrounds.json';
import classesJson from './data/classes.json';
import featsJson from './data/feats.json';
import featuresJson from './data/features.json';
import gearJson from './data/gear.json';
import manifestJson from './data/manifest.json';
import rulesJson from './data/rules.json';
import speciesJson from './data/species.json';
import subclassesJson from './data/subclasses.json';
import subspeciesJson from './data/subspecies.json';
import traitsJson from './data/traits.json';
import weaponsJson from './data/weapons.json';
import type {
  ArmorDef,
  BackgroundDef,
  ClassDef,
  FeatDef,
  FeatureDef,
  GearDef,
  RulesText,
  SpeciesDef,
  SubclassDef,
  SubspeciesDef,
  TraitDef,
  WeaponDef,
} from './types';

export * from './core';
export type * from './types';

function byId<T extends { id: string }>(list: unknown): Record<string, T> {
  return Object.fromEntries((list as T[]).map((x) => [x.id, x]));
}

export const CLASSES = byId<ClassDef>(classesJson);
export const FEATURES = byId<FeatureDef>(featuresJson);
export const SUBCLASSES = byId<SubclassDef>(subclassesJson);
export const SPECIES = byId<SpeciesDef>(speciesJson);
export const SUBSPECIES = byId<SubspeciesDef>(subspeciesJson);
export const TRAITS = byId<TraitDef>(traitsJson);
export const BACKGROUNDS = byId<BackgroundDef>(backgroundsJson);
export const FEATS = byId<FeatDef>(featsJson);
export const WEAPONS = byId<WeaponDef>(weaponsJson);
export const ARMOR = byId<ArmorDef>(armorJson);
export const GEAR = byId<GearDef>(gearJson);
export const RULES_TEXT = rulesJson as RulesText;

/** Attribution required by the SRD's CC-BY-4.0 licence; show it wherever SRD content appears. */
export const SRD_ATTRIBUTION: string = manifestJson.license;
export const SRD_SOURCE = { repo: manifestJson.source, commit: manifestJson.commit };
